### ISSUE TITLE
Change notification Post not being received from Azure when changing a user's contact details (Office location, and others)

### ISSUE THREAD

**Issue by SteveRogers-Enghouse** [microsoftgraph/msgraph-training-changenotifications#17]
Hi,

Has anyone got this tutorial working recently?

I have followed this tutorial using both Visual Studio 2019 enterprise and Visual Studio Code a number of times.
- my Dev system is not a tenanted Azure VM
-- but is logged into Azure via MS Teams and https://portal.azure.com
--- with a user with administrative priveleges

I have struggled with it for almost a week.
- FYI - the video cast was great for the most part, However, I hit problems when I used the slide show to identify the URL to initialiate the subscription.
-- the presenter initially incorrectly types https://localhost:5000/api/notifications
--- and then changes it to http://localhost:5000/api/notifications
---- I probably got it right the first time, but by struggling to get the code fully working afterwards, I probably changed this trying to solve issues and then got stuck, not wanting watch the whole screen cast.  So beware, using the You Tube slider to get actual values.

So - just pointing that out in case anybody else gets stuck at that point when trying to reproduce the tutorial.

I can get Subscriptions and renewals working
- but cannot get the change in https://admin.microsoft.com/AdminPortal#/users contact information
-- to cause a Post in ...
--- NotificationsControllers.cs
---- public ActionResult<string> Post([FromQuery]string validationToken = null)

So, there would not appear to be any issue with NGROK, Azure App Registrations etc.  
- (Azure AD: Permissions, Web URL, Secrets) 
- Nor with appsettings.json: 
-- AppId
-- AppSecret
-- TenantId

public ActionResult<string> Post([FromQuery]string validationToken = null) gets hit only once when I first subscribe
- So Azure is either not able to send the Post back to the correct address
-- or it is being thwarted by my firewall

I can get ....
- private void CheckForUpdates()
-- to work as expected by additionally calling it from 
--- private void CheckSubscriptions(Object stateInfo)

            if (DeltaLink == null)
            {
                CheckForUpdates();
            }
And it delivers the expected results.  So, no problem with the token etc.

So, the only thing that I cannot get working is receiving a Post from Azure when I change a user's contact information.  And the correct NGROK url appears to be correctly passed in ...
- public ActionResult<string> Get()

        [HttpGet]
        public ActionResult<string> Get()
        {
            Console.WriteLine($"ActionResult: Get");
            var graphServiceClient = GetGraphClient();

            var sub = new Microsoft.Graph.Subscription();
            sub.ChangeType = "updated";
            sub.NotificationUrl = config.Ngrok + "/api/notifications";
            sub.Resource = "/users";
            sub.ExpirationDateTime = DateTime.UtcNow.AddMinutes(5);
            sub.ClientState = "SecretClientState";

            var newSubscription = graphServiceClient
              .Subscriptions
              .Request()
              .AddAsync(sub).Result;

            Subscriptions[newSubscription.Id] = newSubscription;

            if (subscriptionTimer == null)
            {
                subscriptionTimer = new Timer(CheckSubscriptions, null, 5000, 15000);
            }

            return $"Subscribed. Id: {newSubscription.Id}, Expiration: {newSubscription.ExpirationDateTime}";
        }

Has anyone fought through this and can help?
- Or even say when they managed to get the Change Notification to work as advertised?

BTW 
- if you run this from Visual Studio and change the launchsettings.JSON file section.
```
    "msgraphapp": {
      "commandName": "Project",

      "launchBrowser": true,

      "launchUrl": "api/notifications",

      "applicationUrl": "http://localhost:5000;https://localhost:5001",

      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
```
- i.e. get the application to initiate itself
- and change the debug to msgraphapp instead of IIS express

Then you do not need to launch http://loacalhost:5000/api/notifications in a browser when you are testing
- this is not the cause, since I do not get a Post when I change a user's contact information without this code modification either.

Can anyone help, please?

**Comment by jasonjoh** [comment]
@SteveRogers-Enghouse I've just tried the sample as-is, as well as the updated project in #18 and in both cases I get a notification when editing a user's mobile phone number. It does sometime take several minutes before Azure sends the notification.

The ngrok viewer (http://localhost:4040/inspect/http while ngrok is running) is pretty handy for seeing what's coming in.

You may want to try cloning this repo and running the project in the ./demos/03-track-changes folder. If that works for you, there may be some config or code differences between the two projects.

**Comment by SteveRogers-Enghouse** [comment]
Hi Jason,

Thanks for your response,  It has saved me some time :)

Since my last post I have created a .net ASP Core Service project that utilises the Classes from this project.  Aiming, to get it self hosting as a Windows service.

I have taken on board your comments, but used the code based on what I had working.
- I commented out my changes to the code that called CheckForUpdates when a subscription was renewed.  Amongst other changes to get things working - which should not be related to this issue.

I have done some tests and by changing a single user's office details, (using the azure Active Directory portal), I can now see the post come back.
- However, in my case it took over 1/2 an hour for the change notification to come through.
-- Which is more than a few minutes as I understand a few :)

A 30 minute delay for a notification is not much use to me.  Since, I may as well poll as often as I can and get the information sooner.

Do you know what triggers the change notification to be sent?
- does it wait for a number of changes before it triggers?
-- is that number on my tenant or based upon other criteria?
-- failing that what is the time limit before it is triggered?

I am investigating the technology with regards to delivering other data from Azure for use in a 3rd party application.
- just using the tutorial to understand how the feasibility works for what I want to achieve

I could try repeating the demo, but have any changes been made that would decrease the delay between the change and the notification?

Thanks,

Steve

**Comment by jasonjoh** [comment]
@piotrci is 30 minutes a reasonable delay between the change happening and the notification being sent for Azure AD?

**Comment by SteveRogers-Enghouse** [comment]
Hi @jasonjoh,

I have been doing some testing and more typically the delay is around 15 minutes, but sometimes it happens much sooner.  And occaisionally, I do not appear to get the notification at all even after waiting for over an hour.

From an application point of view, getting the notification as soon as possible would obviously be beneficial.  But, understanding the delay and its apparent random nature would dictate what an application could use the change notification for.

**Comment by jasonjoh** [comment]
@baywet Are delays like this expected?

**Comment by baywet** [comment]
@jasonjoh no. Most of the times notifications should be received under 10 minutes. If the problem is still persisting I suggest opening a support case.

**Comment by jasonjoh** [comment]
Thanks @baywet. @SteveRogers-Enghouse please do contact [support](https://developer.microsoft.com/graph/support) if you're still having this issue.
