### ISSUE TITLE
How can you setup Azure so that it does not need Ngrok?

### ISSUE THREAD

**Issue by SteveRogers-Enghouse** [microsoftgraph/msgraph-training-changenotifications#20]
Ngrok is great as a developer tool, but for deployment in the real world I would rather not be reliant upon another third-party provider.

How would you go about hosting this with an Azure Tennant without using Ngrok or any similar TCP Tunnel?

**Comment by jasonjoh** [comment]
Ngrok is *only* for development and testing. You could host this on any web hosting platform just like any other HTTPS-protected web API. There's no special requirements.
