### ISSUE TITLE
How to create alive notification url

### ISSUE THREAD

**Issue by liroforum** [microsoftgraph/msgraph-training-changenotifications#4]
After testing with ngrok, how do I create a live notification url? I am pretty new to this and the notification url does not seem to have a great deal of documentation. Could you please point me to the documenations or give me ideas of how can I host/create a notification url?

**Comment by andrewconnell** [comment]
The **notification URL** is just pointing to a publically accessible HTTP API endpoint. NGrok just makes this easier to test locally. You could use Azure web apps or Azure Functions. Either way, the code in the lab can be used to do this.

Check the Azure docs for more details: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-serverless-api
