### ISSUE TITLE
How is Azure Event hub better than delta query

### ISSUE THREAD

**Issue by newbiedev123** [microsoftgraph/msgraph-training-changenotifications#40]
Hi,
I understand we are using the delta query with Graph API change notification (with out event hub) because the Graph API notifications can be sometimes missed out.

So if we are going with the event hub, how is it better. Will the issues with the missed Graph API notification still be a problem? Or again should the Event hub option be used with the Azure Event Hub?

Thanks in advance.

**Comment by jasonjoh** [comment]
I'm not sure if I'm answering your question exactly, but here's my perspective. One isn't "better" than the other, it's more of a matter of choosing the right tool for your needs.

- Delta query is essentially "polling" for changes. Your app has to manage how often you poll, but if it's not crucial that you get notified as events happen, then polling is easier to implement. There's no need to configure a notification endpoint (like Azure Event Hub), you can poll from a simple app. You also don't need to worry about missed notifications, as you're polling and getting a diff.
- Change notification (which to be clear, is the approach the code in this repository uses) is a close-to-real-time notification, meaning that in most cases, shortly after something happens, you will get notified. It's a bit more involved to set up, as you need a notification endpoint. It doesn't have to be Azure Event Hub, you could write your own custom web app in any language you like that accepts the notification payloads (similar to the code in this repo).

Event Hub's advantage is you don't have to write code to handle ingesting the incoming events from Graph. Missed notifications would still be a possibility.

**Comment by newbiedev123** [comment]
Thanks @jasonjoh
