### ISSUE TITLE
Eventhubs publishing validation failed 

### ISSUE THREAD

**Issue by newbiedev123** [microsoftgraph/msgraph-training-changenotifications#41]
Hi,
I am using event hubs for getting change notification. While creating the subscritpion I am getting the below error.

Microsoft.Graph.ServiceException: 'Code: InvalidRequest
Message: Client EventHubs publishing validation failed Object reference not set to an instance of an object.

I followed the steps in the below link to create Azure Key vault and Azure Event Hub.

https://docs.microsoft.com/en-us/graph/change-notifications-delivery#configuring-the-azure-event-hub
Thanks

**Comment by jasonjoh** [comment]
@newbiedev123 unfortunately we aren't set up to provide troubleshooting support through sample repositories. You're best bet would be to open a support ticket via the Azure portal to get assistance with your Event Hub.
