### ISSUE TITLE
Making this api to be hosted in azure and running 24*7

### ISSUE THREAD

**Issue by liroforum** [microsoftgraph/msgraph-training-changenotifications#5]
Hi,

My question might seem a bit silly, but I am new to all these so a bit confused.

So I have replicated this api and it all works when launched. 

I am planning to host this api in Azure.

But my doubt is, I want this application to be running all the time and not just when the api/notification is called. I mean this application should be live waiting for notification 24*7.

Is the above possible? 

Thanks

**Comment by andrewconnell** [comment]
Yup... Azure web apps & Azure Functions are always "on". There is a setting with Azure Functions that you can run in reserved / consumption mode... the former is "always warmed up", the latter only charges you when you are running. It works by spinning up your Azure function when it receives a request and can take a few seconds to get started.

**Comment by liroforum** [comment]
So does that mean after I have hosted this API in azure, I will never have to call the api/notification endpoint? Everything will work automatically when the web app is created and running?
I was a bit confused because api/notification is a httpget method, so will that not need a http request to trigger it? 
Again maybe I was thinking a bit silly. I was thinking to create a console application which calls this api/notification endpoint. And add the .exe of the console application to the startup of out IIS server, to make it running all the time.

I am not sure if the above will work, just my thougt.

But am I thinking too much?

**Comment by liroforum** [comment]
Regarding the Webapp you mentioned above, is it enough to create an empty webapp in azure? or does it need any methods in it?

**Comment by andrewconnell** [comment]
Have you watched the screencast & gone through the lab? It explains how everything works.

There's nothing "automatic" about this. The endpoint you create simply responds to posts from the MS Graph notifications. It serves two purposes: (1) validate the subscription when created & (2) receive notifications based on what you subscribe to.

YOU don't call your endpoint, you tell MS Graph to call it when something happens.

Suggest you read up on the docs too... it's probably best to post these types of understanding questions to the docs feedback: https://docs.microsoft.com/en-us/graph/webhooks

**Comment by andrewconnell** [comment]
@liroforum said
> Regarding the Webapp you mentioned above, is it enough to create an empty webapp in azure? or does it need any methods in it?

Absolutely not... you have to implement the API that will receive the notifications from MS Graph that you're subscribing to. 

Think of it like a telephone. Buying a phone (the Azure function / web app) and giving your number (the URL) out to your friend (MSGraph) doesn't do anything to make your communications better. Someone has to be on the other end of the phone to pick it up and answer (the API).

**Comment by liroforum** [comment]
Thanks Andrew. That makes sense now. I have hosted the API in Azure and doing my testing now. Thanks for your help and support.
