### ISSUE TITLE
Timer stops unexpectedly

### ISSUE THREAD

**Issue by liroforum** [microsoftgraph/msgraph-training-changenotifications#7]
Hi ,
I follwed this code and deployed the code to production. It works fine, but some times the timer automatically stops without a warning and subscription is not renewed. Is there a way around?

**Comment by andrewconnell** [comment]
A more reliable approach would be to create an external service, such as an Azure Function, that is set on a schedule to monitor the expiration of the subscription & automatically renew it.

This is just a demo solution used for educational purposes... if the application stops/crashes for any reason, the timer approach will fail.
